### ISSUE TITLE
Release for Windows Store and Xbox

### ISSUE THREAD

**Issue by dkanada** [chaosinnovator/jellyfin-uwp#14]
We were just talking about Xbox support again recently, and I was wondering if you'd be interested in transferring this repository and starting to publish releases? I'm not sure what requirements Microsoft has for apps but if it would pass their guidelines today we'd love to get it done.

**Comment by Clickbaitcake** [comment]
I'd like to bump this thread. Getting the UWP into the Microsoft Store would be great. If the code is ready to go id be happy to help get things moving on the Microsoft side? 

[Just need to cover the points on this checklist and submit.](https://docs.microsoft.com/en-gb/windows/uwp/publish/app-submissions)

**Comment by dkanada** [comment]
We have a repository at [jellyfin-uwp](https://github.com/jellyfin/jellyfin-uwp) now, and are working on a release. @chaosinnovator I'll close this for now, but feel free to reopen it anytime!

**Comment by Clickbaitcake** [comment]
I think the links on Jellyfin.org should be udated to point to that new repo instead in this case. Do you agree? 
https://jellyfin.org/docs/general/clients/index.html

**Comment by dkanada** [comment]
Yeah, that seems reasonable.
